/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.rummypresentacion.vista;

import itson.rummypresentacion.controlador.ControlTurno;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Dana Chavez
 */
public class UI_TurnoJugador extends javax.swing.JFrame implements UI_Componente {

    private String id = "root";
    private List<UI_Componente> componentes;

    private UI_Mano uiMano;
    private UI_Tablero uiTablero;

    private ControlTurno control;

    public UI_TurnoJugador() {
        initComponents();
        inicializarComponentesVisuales();
    }

    public void mostrarMensaje(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    private void inicializarComponentesVisuales() {
        uiMano = new UI_Mano();
        uiTablero = new UI_Tablero();

        jPanelContenedorMano.setLayout(new BorderLayout());
        jPanelContenedorTablero.setLayout(new BorderLayout());

        jPanelContenedorMano.add(uiMano, BorderLayout.CENTER);
        jPanelContenedorTablero.add(uiTablero, BorderLayout.CENTER);

        uiMano.setTablero(uiTablero);
        uiTablero.setMano(uiMano);

        configurarBotonesMock();
    }

    private void configurarBotonesMock() {

        btnTerminarTurno.addActionListener(e -> {
            System.out.println("Botón Terminar Turno clickeado");
        });
    }

    public void agregarFichaAMano(int numero, Color color) {
        uiMano.agregarFicha(new UI_Ficha(numero, color));
    }

    public void cargarManoEjemplo() {
        agregarFichaAMano(1, Color.RED);
        agregarFichaAMano(2, Color.RED);
        agregarFichaAMano(3, Color.RED);
        agregarFichaAMano(7, Color.BLUE);
        agregarFichaAMano(7, Color.GREEN);
        agregarFichaAMano(7, Color.YELLOW);
        agregarFichaAMano(4, Color.RED);
        agregarFichaAMano(5, Color.BLUE);
        agregarFichaAMano(6, Color.GREEN);
    }

    public UI_Tablero getUITablero() {
        return uiTablero;
    }

    public void limpiarMano() {
        uiMano.limpiarMano();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTomarFicha = new javax.swing.JButton();
        btnTerminarTurno = new javax.swing.JButton();
        jPanelContenedorMano = new javax.swing.JPanel();
        jPanelContenedorTablero = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTomarFicha.setText("TOMAR FICHA");
        btnTomarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarFichaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTomarFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 1010, 100, 80));

        btnTerminarTurno.setText("TERMINAR TURNO");
        getContentPane().add(btnTerminarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 910, 100, 80));

        jPanelContenedorMano.setBackground(new java.awt.Color(39, 41, 72));
        jPanelContenedorMano.setPreferredSize(new java.awt.Dimension(1418, 235));
        jPanelContenedorMano.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelContenedorMano, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 905, 1450, 190));

        javax.swing.GroupLayout jPanelContenedorTableroLayout = new javax.swing.GroupLayout(jPanelContenedorTablero);
        jPanelContenedorTablero.setLayout(jPanelContenedorTableroLayout);
        jPanelContenedorTableroLayout.setHorizontalGroup(
            jPanelContenedorTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        jPanelContenedorTableroLayout.setVerticalGroup(
            jPanelContenedorTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelContenedorTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 1230, 660));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_TurnoJugador.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTomarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTomarFichaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminarTurno;
    private javax.swing.JButton btnTomarFicha;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanelContenedorMano;
    private javax.swing.JPanel jPanelContenedorTablero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void ocultar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void actualizar() {
        this.revalidate();
        this.repaint();
    }

    @Override
    public void agregarComponente(UI_Componente componente) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void removerComponente(UI_Componente componente) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public UI_Componente getComponente(int index) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public List<UI_Componente> getComponentes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
}
