/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.rummypresentacion.ejercerturno;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Dana Chavez
 */
public class UI_Tablero extends javax.swing.JPanel {

    private int baseCellWidth = 120;
    private int baseCellHeight = 140;

    private int filas = 4;
    private int columnas = 10;

    public UI_Tablero() {
        setPreferredSize(new Dimension(1230, 660));
        setBackground(new Color(230, 230, 230));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;

        int cellWidth = Math.max(getWidth() / columnas, 40);   
        int cellHeight = Math.max(getHeight() / filas, 40);

        g2.setColor(Color.LIGHT_GRAY);
        for (int r = 0; r < filas; r++) {
            for (int c = 0; c < columnas; c++) {
                int x = c * cellWidth;
                int y = r * cellHeight;
                g2.drawRect(x, y, cellWidth, cellHeight);
            }
        }
    }

    public void setGridSize(int filas, int columnas) {
        this.filas = filas;
        this.columnas = columnas;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
