/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.rummypresentacion.vista;

import itson.rummydtos.FichaDTO;
import itson.rummydtos.GrupoDTO;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDropEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class UI_Tablero extends javax.swing.JPanel {

    private final UI_TurnoJugador ventanaPrincipal;
    private final List<UI_Grupo> gruposVisuales = new ArrayList<>();

    public UI_Tablero(UI_TurnoJugador ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        configurarPanel();
        habilitarDrop();
    }

    private void configurarPanel() {
        setOpaque(false);
        setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
        setPreferredSize(new Dimension(803, 448));
    }

    private void habilitarDrop() {
        setDropTarget(new DropTarget(this, new DropTargetAdapter() {
            @Override
            public void drop(DropTargetDropEvent evt) {
                try {
                    evt.acceptDrop(DnDConstants.ACTION_MOVE);

                    Object data = evt.getTransferable()
                            .getTransferData(FichaTransferable.FICHA_FLAVOR);

                    if (!(data instanceof FichaTransferable)) {
                        evt.dropComplete(false);
                        return;
                    }

                    FichaTransferable ft = (FichaTransferable) data;
                    List<FichaDTO> fichas = ft.getFichas();

                    if (fichas == null || fichas.isEmpty()) {
                        evt.dropComplete(false);
                        return;
                    }

                    crearGrupoVisual(fichas);
                    evt.dropComplete(true);

                    if (ventanaPrincipal != null) {
                        ventanaPrincipal.notificarGrupoCreado(fichas);
                    }

                } catch (Exception ex) {
                    ex.printStackTrace();
                    evt.dropComplete(false);
                }
            }
        }));
    }

    private void crearGrupoVisual(List<FichaDTO> fichas) {
        String idGrupo = java.util.UUID.randomUUID().toString();
        UI_Grupo grupoPanel = new UI_Grupo(idGrupo, fichas, this);
        gruposVisuales.add(grupoPanel);
        add(grupoPanel);
        revalidate();
        repaint();
    }

    public void setGruposDesdeDTO(List<GrupoDTO> gruposDTO) {
        for (UI_Grupo grupo : gruposVisuales) {
            remove(grupo);
        }
        gruposVisuales.clear();
        if (gruposDTO != null) {
            List<GrupoDTO> gruposOrdenados = new ArrayList<>(gruposDTO);
            gruposOrdenados.sort((g1, g2) -> g1.getId().compareTo(g2.getId()));
            
            for (GrupoDTO dto : gruposOrdenados) {
                List<FichaDTO> fichasGrupo = (dto.getFichas() != null)
                        ? dto.getFichas()
                        : new ArrayList<>();
                UI_Grupo grupoPanel = new UI_Grupo(dto.getId(), fichasGrupo, this);

                gruposVisuales.add(grupoPanel);
                add(grupoPanel);
            }
        }
        revalidate();
        repaint();
    }

    public List<UI_Grupo> getGruposVisuales() {
        return new ArrayList<UI_Grupo>(gruposVisuales);
    }

    public UI_TurnoJugador getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void removerFichasDeOtrosContenedores(List<FichaDTO> fichasMovidas, Object destino) {
        Set<String> ids = new HashSet<>();
        for (FichaDTO f : fichasMovidas) {
            ids.add(f.getId());
        }
        if (ventanaPrincipal != null) {
            UI_Mano mano = ventanaPrincipal.getUIMano();
            if (mano != null && mano != destino) {
                mano.removerFichasPorId(ids);
            }
        }
        for (UI_Grupo grupo : gruposVisuales) {
            if (grupo != destino) {
                grupo.removerFichasPorId(ids);
            }
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(803, 448));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
